spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myhotel
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: LbvF88tDf
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

clients:
  description:
    url: localhost:8082/api/description
