spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myhotel
    driver-class-name: org.postgresql.Driver
    username: prood_567
    password: treck-prod
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true